- lib/chunkify.js
- test/chunkify_test.js
> Quote file paths before passing to vnu.jar

- README.md
[Code Climate](https://codeclimate.com/) provides free automated code review for open source projects.
> Add Code Climate badge to README

- .editorconfig
- .jshintrc
- Gruntfile.js
- README.md
- lib/htmllint.js
- lib/reporters/checkstyle.js
- package.json
- tasks/html.js
- test/checkstyle_test.js
- test/html_test.js
- test/invalid.html
- test/invalid.php
- test/json_test.js
- test/reporters_test.js
- test/support/custom_reporter.js
- test/support/expected_results.js
- test/valid.html
https://github.com/jzaefferer/grunt-html/compare/jzaefferer:master...XhmikosR:lint?w=1
> Lint tweaks

- .travis.yml
- appveyor.yml
- lib/htmllint.js
- package.json
- test/chunkify_test.js
Sorry for not splitting this up, let me know if you need any changes.
> Minor tweaks

- .travis.yml
- appveyor.yml
- lib/htmllint.js
- package.json
@jzaefferer: if you want me to split this or make any changes just let me know.
This fixes #86.
> Update dependencies and validator to the latest versions

- README.md
- lib/reporters.js
- lib/reporters/junit.js
- test/junit_test.js
Created a JUnit reporter so that our CI server can better report validation failures. If you think it's useful please feel free to merge it into the core.
Code style is based on the checkstyle reporter.
Cheers and thanks!
> Added JUnit reporter

- .travis.yml
- appveyor.yml
Include node.js 7, remove 0.12 and 5. Also, remove redundant directives from .travis.yml.
/CC @jzaefferer
> Update CI configs.

- package.json
https://github.com/validator/validator/releases/tag/17.7.0
> Bump vnu-jar to June 2017 release

- package-lock.json
- package.json
https://github.com/validator/validator/releases/tag/18.8.29
> feat: Bump vnu-jar to 18.8.29

- .travis.yml
- appveyor.yml
- package-lock.json
- package.json
Note that this will need to be a major version bump.
~~There's no hurry to merge this, just FYI.~~
> Drop support for Node.js 4.x.

- .gitignore
- .travis.yml
- README.md
- package-lock.json
- package.json
Fixes #127 
Currently I've only included the lib files.
> Add nyc and coveralls.

- .eslintrc.json
- Gruntfile.js
- lib/chunkify.js
- lib/htmllint.js
- lib/javadetect.js
- lib/reporters.js
- lib/reporters/checkstyle.js
- lib/reporters/json.js
- lib/reporters/junit.js
- package-lock.json
- package.json
- tasks/html.js
- test/checkstyle_test.js
- test/chunkify_test.js
- test/html_test.js
- test/json_test.js
- test/junit_test.js
- test/reporters_test.js
- test/support/custom_reporter.js
- test/support/expected_results.js
I know this is opinionated but those extra spaces were so annoying to me. :/
Anyway, feel free to tweak the rules; I went with what the config I'm using myself.
**Requires #125 merged!**
See the non-whitespace diff https://github.com/jzaefferer/grunt-html/pull/126/files?utf8=%E2%9C%93&diff=unified&w=1
TODO:
>  ES6-ify code base and switch style.

- lib/chunkify.js
- test/chunkify_test.js
I'm not sure about this check `chunk.length + (files[f].length + 1) > maxChars`. So if anyone can suggest how to make the function clearer and even tighten the tests, let me know or push here.
Fixes #129
> Remove spaces from chunkify().

- lib/htmllint.js
Also make constants uppercase.
> Use the Array spread operator and `for...of`.

- .github/workflows/test.yml
- package-lock.json
- package.json
* chalk   ^3.0.0  →   ^4.0.0
* nyc    ^15.0.0  →  ^15.0.1
* xo     ^0.25.3  →  ^0.29.1
TODO:
> Update dependencies and drop Node.js < 10 support

- Gruntfile.js
- package-lock.json
- package.json
- test/checkstyle_test.js
- test/chunkify_test.js
- test/html_test.js
- test/json_test.js
- test/junit_test.js
- test/reporters_test.js
Non-whitespace diff: <https://github.com/validator/grunt-html/pull/156/files?w=1>
> Switch to mocha

- .github/workflows/test.yml
- .gitignore
- package-lock.json
- package.json
It seems there's a difference in the coverage with c8. Not sure which one is right...
> Switch to c8 for coverage

- Gruntfile.js
- package-lock.json
- package.json
It's deprecated but I'm not aware of any replacements...
> Add `time-grunt`

- package-lock.json
- package.json
- test/helpers/expected_results.js
- test/helpers/run.js
- test/html_test.js
- test/server_test.js
Added tests for `config.server`
Fixes #135
> Add server tests

- .github/workflows/codeql.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
* update CodeQL workflow
* remove git credentials after checkout
* switch to Node.js 18 LTS
* add `workflow_dispatch`
> Update CI config
